#Server Side
paths:
  PERSONA_FILE: "server/prompt/persona.txt"
  CHUNKING_INSTRUCTION: "server/prompt/chunk_instruct.txt"
  VOICE_MODEL: "server/models/voice/"
  CHAT_HISTORY: "server/chat/chat_history.json"
  CHAT_CHUNKS: "server/chat/chat_chunks.json"

settings:
  MODEL: "llama-3.1-8b-instant"
  TEMPERATURE: 1
  SPEAKER_ID: 0
  SPEED: 0.897

# Client
