name: Aino
channels:
  - defaults
  - nvidia/label/cuda-12.8.0
dependencies:
  - aom=3.12.1
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=25.1.0
  - asttokens=3.0.0
  - async-lru=2.0.5
  - attrs=25.4.0
  - babel=2.17.0
  - beautifulsoup4=4.14.2
  - blas=1.0
  - bleach=6.3.0
  - bottleneck=1.4.2
  - brotlicffi=1.1.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.11.4
  - cairo=1.18.4
  - cffi=2.0.0
  - charset-normalizer=3.4.4
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cuda=12.8.0
  - cuda-cccl_win-64=12.8.55
  - cuda-command-line-tools=12.8.0
  - cuda-compiler=12.8.0
  - cuda-crt-dev_win-64=12.8.61
  - cuda-crt-tools=12.8.61
  - cuda-cudart=12.8.57
  - cuda-cudart-dev=12.8.57
  - cuda-cudart-dev_win-64=12.8.57
  - cuda-cudart-static=12.8.57
  - cuda-cudart-static_win-64=12.8.57
  - cuda-cudart_win-64=12.8.57
  - cuda-cuobjdump=12.8.55
  - cuda-cupti=12.8.57
  - cuda-cupti-dev=12.8.57
  - cuda-cuxxfilt=12.8.55
  - cuda-libraries=12.8.0
  - cuda-libraries-dev=12.8.0
  - cuda-nvcc=12.8.61
  - cuda-nvcc-dev_win-64=12.8.61
  - cuda-nvcc-impl=12.8.61
  - cuda-nvcc-tools=12.8.61
  - cuda-nvcc_win-64=12.8.61
  - cuda-nvdisasm=12.8.55
  - cuda-nvml-dev=12.8.55
  - cuda-nvprof=12.8.57
  - cuda-nvprune=12.8.55
  - cuda-nvrtc=12.8.61
  - cuda-nvrtc-dev=12.8.61
  - cuda-nvvm-dev_win-64=12.8.61
  - cuda-nvvm-impl=12.8.61
  - cuda-nvvm-tools=12.8.61
  - cuda-nvvp=12.8.57
  - cuda-opencl=12.8.55
  - cuda-opencl-dev=12.8.55
  - cuda-profiler-api=12.8.55
  - cuda-runtime=12.8.0
  - cuda-sanitizer-api=12.8.55
  - cuda-toolkit=12.8.0
  - cuda-tools=12.8.0
  - cuda-version=12.8
  - cuda-visual-tools=12.8.0
  - cycler=0.11.0
  - dav1d=1.2.1
  - decorator=5.2.1
  - defusedxml=0.7.1
  - executing=2.2.1
  - expat=2.7.3
  - ffmpeg=6.1.1
  - filelock=3.20.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fsspec=2025.10.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - h11=0.16.0
  - harfbuzz=10.2.0
  - html5lib=1.1
  - httpcore=1.0.9
  - httpx=0.28.1
  - icu=73.1
  - idna=3.11
  - importlib-metadata=8.7.0
  - intel-openmp=2023.1.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - json5=0.12.1
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.9.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.7
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.28.0
  - jupyterlab_widgets=3.0.15
  - khronos-opencl-icd-loader=2025.07.22
  - kiwisolver=1.4.9
  - lcms2=2.16
  - lerc=3.0
  - libabseil=20250127.0
  - libcublas=12.8.3.14
  - libcublas-dev=12.8.3.14
  - libcufft=11.3.3.41
  - libcufft-dev=11.3.3.41
  - libcurand=10.3.9.55
  - libcurand-dev=10.3.9.55
  - libcusolver=11.7.2.55
  - libcusolver-dev=11.7.2.55
  - libcusparse=12.5.7.53
  - libcusparse-dev=12.5.7.53
  - libdeflate=1.17
  - libffi=3.4.4
  - libglib=2.84.4
  - libiconv=1.16
  - libkrb5=1.21.3
  - libnpp=12.3.3.65
  - libnpp-dev=12.3.3.65
  - libnvfatbin=12.8.55
  - libnvfatbin-dev=12.8.55
  - libnvjitlink=12.8.61
  - libnvjitlink-dev=12.8.61
  - libnvjpeg=12.3.5.57
  - libnvjpeg-dev=12.3.5.57
  - libogg=1.3.5
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libtheora=1.2.0
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libwebp-base=1.6.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - matplotlib=3.10.6
  - matplotlib-base=3.10.6
  - matplotlib-inline=0.2.1
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - nest-asyncio=1.6.0
  - networkx=3.5
  - notebook=7.4.5
  - notebook-shim=0.2.4
  - nsight-compute=2025.1.0.14
  - numexpr=2.11.0
  - opencl-headers=2025.07.22
  - openjpeg=2.5.2
  - openssl=3.0.18
  - opentelemetry-api=1.38.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.3
  - pandoc=3.8
  - pandocfilters=1.5.1
  - parso=0.8.5
  - pcre2=10.46
  - pip=25.3
  - pixman=0.46.4
  - platformdirs=4.5.0
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - pure_eval=0.2.3
  - pycparser=2.23
  - pygments=2.19.2
  - pyparsing=3.2.5
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - pysocks=1.7.1
  - python=3.11.14
  - python-dateutil=2.9.0post0
  - python-fastjsonschema=2.21.2
  - python-json-logger=3.2.1
  - python-tzdata=2025.2
  - pytz=2025.2
  - pywin32=311
  - pywinpty=2.0.15
  - pyyaml=6.0.3
  - pyzmq=27.1.0
  - qtbase=6.7.3
  - qtconsole=5.7.0
  - qtdeclarative=6.7.3
  - qtpy=2.4.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - referencing=0.37.0
  - requests=2.32.5
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rpds-py=0.28.0
  - send2trash=1.8.2
  - sip=6.10.0
  - six=1.17.0
  - sleef=3.5.1
  - soupsieve=2.5
  - sqlite=3.51.0
  - stack_data=0.6.3
  - sympy=1.14.0
  - tbb=2021.8.0
  - tbb-devel=2021.8.0
  - terminado=0.18.1
  - tinycss2=1.4.0
  - tk=8.6.15
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - urllib3=2.5.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - vs2017_win-64=19.16.27032.1
  - vswhere=3.1.7
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - win_inet_pton=1.1.0
  - winpty=0.4.3
  - xz=5.6.4
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.11.0
      - appdirs==1.4.4
      - asyncio==4.0.0
      - bidict==0.23.1
      - cachetools==6.2.1
      - certifi==2025.10.5
      - click==8.3.1
      - cmake==4.1.2
      - coloredlogs==15.0.1
      - debugpy==1.8.17
      - distro==1.9.0
      - dnspython==2.8.0
      - dotenv==0.9.9
      - fastapi==0.121.3
      - fastembed-gpu==0.7.3
      - flatbuffers==25.9.23
      - fs==2.4.16
      - google-auth==2.42.1
      - google-genai==1.47.0
      - groq==0.33.0
      - huggingface-hub==0.36.0
      - humanfriendly==10.0
      - ipykernel==7.1.0
      - ipython==9.6.0
      - jiter==0.11.1
      - joblib==1.5.2
      - jupyter-core==5.9.1
      - loguru==0.7.3
      - markupsafe==3.0.3
      - mmh3==5.2.0
      - numpy==1.26.4
      - onnx==1.17.0
      - onnxruntime-gpu==1.23.2
      - pathlib==1.0.1
      - pillow==11.3.0
      - protobuf==6.33.0
      - psutil==7.1.2
      - py-rust-stemmers==0.1.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyaudio==0.2.14
      - pydantic==2.12.3
      - pydantic-core==2.41.4
      - pymongo==4.15.3
      - pyreadline3==3.5.4
      - python-dotenv==1.2.1
      - python-engineio==4.12.3
      - python-socketio==5.14.3
      - regex==2025.10.23
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.16.3
      - sentence-transformers==5.1.2
      - setuptools==80.9.0
      - sherpa-onnx==1.12.13+cuda12.cudnn9
      - simple-websocket==1.1.0
      - sniffio==1.3.1
      - sounddevice==0.5.3
      - starlette==0.50.0
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tokenizers==0.22.1
      - torch==2.9.0
      - tornado==6.5.2
      - tqdm==4.67.1
      - transformers==4.57.1
      - typing-inspection==0.4.2
      - uv==0.9.7
      - uvicorn==0.38.0
      - wcwidth==0.2.14
      - websockets==15.0.1
      - win32-setctime==1.2.0
      - wsproto==1.3.2
prefix: C:\Users\ikhsa\miniconda3\envs\Aino
